services:
  cairo-coder-postgres:
    image: pgvector/pgvector:pg17
    container_name: 'cairo-coder-postgres'
    shm_size: 1g
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cairo_coder
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U yo -d cairo_coder_db']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  cairo-coder-backend:
    container_name: 'cairo-coder-backend'
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - 3001:3001
    env_file:
      - packages/backend/.env
    depends_on:
      cairo-coder-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cairo_coder

  cairo-coder-ingester:
    build:
      context: .
      dockerfile: ingester.dockerfile
    profiles: ['ingester']
    depends_on:
      cairo-coder-postgres:
        condition: service_healthy
    networks:
      - cairo_coder

networks:
  cairo_coder:

volumes:
  postgres_data:
