[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""
DEEPSEEK = ""
GEMINI = ""

[API_ENDPOINTS]
OLLAMA = ""

[VECTOR_DB]
POSTGRES_USER="cairocoder"
POSTGRES_PASSWORD="cairocoder"
POSTGRES_ROOT_DB="cairocoder"
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"

[GENERAL]
PORT = 3_001
SIMILARITY_MEASURE = "cosine"

[HOSTED_MODE]
DEFAULT_CHAT_PROVIDER = "gemini"
DEFAULT_CHAT_MODEL = "Gemini Flash 2.5"
DEFAULT_FAST_CHAT_PROVIDER = "gemini"
DEFAULT_FAST_CHAT_MODEL = "Gemini Flash 2.5"
DEFAULT_EMBEDDING_PROVIDER = "openai"
DEFAULT_EMBEDDING_MODEL = "Text embedding 3 large"