# Cairo Coder Configuration
[VECTOR_DB]
POSTGRES_USER = "cairocoder"
POSTGRES_PASSWORD = "cairocoder"
POSTGRES_DB = "cairocoder"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
POSTGRES_TABLE_NAME = "documents"
SIMILARITY_MEASURE = "cosine"
